#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$DATABASE_USER" --dbname "$DATABASE_NAME" <<-EOSQL
    CREATE USER $POSTGRES_USER_NAME WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASSWORD';
    CREATE DATABASE $POSTGRES_DB_NAME;
    ALTER DATABASE $POSTGRES_DB_NAME OWNER TO $POSTGRES_USER_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_NAME TO $POSTGRES_USER_NAME;
    ALTER USER $POSTGRES_USER_NAME CREATEDB;
EOSQL