version: '3.7'

services:
  nginx:
    container_name: "${WEBSERVER_CONTAINER_NAME}"
    image: nginx:1.21.6
    volumes:
      - ../:/srv
      - ./nginx/mteck.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - "8080:80"
    links:
      - php
    networks:
      - mteck-network

  php:
    container_name: "${APPLICATION_CONTAINER_NAME}"
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    volumes:
      - ..:/srv
      - ./php/conf.d/app.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
      - $HOME/.composer/cache:/home/dev/.composer/cache
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - mteck-network
    depends_on:
      - postgres

  postgres:
    container_name: "${DATABASE_CONTAINER_NAME}"
    build:
      dockerfile: postgres/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
      - POSTGRES_USER_NAME=$POSTGRES_USER_NAME
      - POSTGRES_USER_PASSWORD=$POSTGRES_USER_PASSWORD
    volumes:
      - mteck:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mteck-network

volumes:
  mteck:
    name: mteck_database_data

networks:
  mteck-network:
    name: mteck-network
