version: '3.7'

services:
#  pgAdmin:
#    restart: always
#    image: dpage/pgadmin4
#    ports:
#      - "5000:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
#    depends_on:
#      - postgres
#    networks:
#      - mteck-network

  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5001:5432"
    volumes:
      - mteck_data:/var/lib/postgresql/data:rw
    networks:
      - mteck-network

  php:
    container_name: php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    build:
      context: php
    volumes:
      - ..:/srv
      - ./php/conf.d/app.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
      - $HOME/.composer/cache:/home/dev/.composer/cache
    depends_on:
      - postgres
    networks:
      - mteck-network

  nginx:
    container_name: nginx
    image: nginx:1.21.6
    volumes:
      - ../:/srv
      - ./nginx/mteck.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - "8081:80"
    links:
      - php
    networks:
      - mteck-network

networks:
  mteck-network:
    name: mteck-network

volumes:
  mteck_data:
    name: mteck_data