controller_core:
    resource: ../src/Core/Infrastructure/Controller/
    type: attribute

controller_product:
    resource: ../src/Product/Infrastructure/Controller/
    type: attribute

controller_users:
    resource: ../src/Users/Infrastructure/Controller/
    type: attribute